sudo: required

services:
  - docker
  - redis-server

env:
  global:
    - HE_GITHUB_SECRET=test-secret
    - HE_GITHUB_CLIENTID=test-clientid
    - HE_GITHUB_CALLBACK_URL=http://127.0.0.1
    - HE_SESSION_SECRET=test-sessionsecret
    - HE_ENC_KEY=8556e651184da5c8d5ab8f3236ef1164d8b5e9cff704025d9212d32408eeffc9
    - HE_ENC_HMAC=40996c4c2b3a0db82dbd469395a3fc7e04b1925f729d2ebc2232c5751d70a390
    - HE_SERVER_URL=http://127.0.0.1
    - HE_VERSION=0.17.0

language: node_js

node_js:
  - 8

notifications:
  email: false

branches:
  only:
    - master

before_script:
  - npm version $HE_VERSION

after_success:
  - sudo apt-get update && sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull stono/hawkeye.ninja
  - docker pull stono/hawkeye.ninja-worker
  - docker pull stono/hawkeye.ninja-oneshot
  - docker pull stono/hawkeye:$HE_VERSION
  - docker tag stono/hawkeye:$HE_VERSION stono/hawkeye:latest
  - docker build -f Dockerfile --build-arg HE_VERSION=$HE_VERSION -t stono/hawkeye.ninja --cache-from stono/hawkeye.ninja .
  - docker build -f Dockerfile.worker --build-arg HE_VERSION=$HE_VERSION -t stono/hawkeye.ninja-worker --cache-from stono/hawkeye.ninja-worker .
  - docker build -f Dockerfile.oneshot --build-arg HE_VERSION=$HE_VERSION -t stono/hawkeye.ninja-oneshot --cache-from stono/hawkeye.ninja-oneshot .
  - docker tag stono/hawkeye.ninja-oneshot:latest stono/hawkeye.ninja-oneshot:$HE_VERSION
  - docker push stono/hawkeye.ninja
  - docker push stono/hawkeye.ninja-worker
  - docker push stono/hawkeye.ninja-oneshot
  - docker push stono/hawkeye.ninja-oneshot:$HE_VERSION
