sudo: required

services:
  - docker
  - redis-server

env:
  - HE_GITHUB_SECRET=test-secret
  - HE_GITHUB_CLIENTID=test-clientid
  - HE_GITHUB_CALLBACK_URL=http://127.0.0.1
  - HE_SESSION_SECRET=test-sessionsecret
  - HE_REDIS_PASSWORD=test-redispassword

language: node_js

node_js:
  - 7

notifications:
  email: false

branches:
  only:
    - master

after_success:
  - docker build -t stono/hawkeye.ninja .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push stono/hawkeye.ninja
