sudo: required

services:
  - docker
  - redis-server

env:
  global:
    - HE_GITHUB_SECRET=test-secret
    - HE_GITHUB_CLIENTID=test-clientid
    - HE_GITHUB_CALLBACK_URL=http://127.0.0.1
    - HE_SESSION_SECRET=test-sessionsecret
    - HE_REDIS_PASSWORD=test-redispassword

language: node_js

node_js:
  - 7

notifications:
  email: false

branches:
  only:
    - master

after_success:
  - sudo apt-get update && sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull stono/hawkeye.ninja
  - docker pull stono/hawkeye.ninja-worker
  - docker pull stono/hawkeye.ninja-oneshot
  - docker build -f Dockerfile -t stono/hawkeye.ninja --cache-from stono/hawkeye.ninja .
  - docker build -f Dockerfile.worker -t stono/hawkeye.ninja-worker --cache-from stono/hawkeye.ninja-worker .
  - docker build -f Dockerfile.oneshot -t stono/hawkeye.ninja-oneshot --cache-from stono/hawkeye.ninja-oneshot .
  - docker push stono/hawkeye.ninja
  - docker push stono/hawkeye.ninja-worker
  - docker push stono/hawkeye.ninja-oneshot
