version: '2'

services:
  hawkeye:
    image: stono/hawkeye.ninja
    build: .
    environment:
      - HE_GITHUB_SECRET
      - HE_GITHUB_CLIENTID
      - HE_GITHUB_CALLBACK_URL
      - HE_SESSION_SECRET
      - HE_REDIS_PASSWORD
    ports:
      - 5000
    volumes:
      - ./lib:/app/lib
