version: '2'

services:
  web:
    image: stono/hawkeye.ninja
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - HE_GITHUB_SECRET
      - HE_GITHUB_CLIENTID
      - HE_GITHUB_CALLBACK_URL
      - HE_SESSION_SECRET
      - HE_SERVER_URL=http://web
      - HE_REDIS_PASSWORD
      - HE_ENC_KEY
      - HE_ENC_HMAC
      - HE_MAIL_API_KEY
      - HE_DAL_GZIP
      - NODE_ENV=prod
      - DEBUG
    ports:
      - 5000:5000

  worker:
    image: stono/hawkeye.ninja-worker
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: npm run worker
    depends_on:
      - redis
    environment:
      - HE_GITHUB_SECRET
      - HE_GITHUB_CLIENTID
      - HE_GITHUB_CALLBACK_URL
      - HE_SESSION_SECRET
      - HE_SERVER_URL=http://web
      - HE_REDIS_PASSWORD
      - HE_ENC_KEY
      - HE_ENC_HMAC
      - HE_MAIL_API_KEY
      - HE_DAL_GZIP
      - NODE_ENV=prod
      - DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  oneshot:
    image: stono/hawkeye.ninja-oneshot
    command: /bin/true
    build:
      context: .
      dockerfile: Dockerfile.oneshot

  redis:
    image: redis:alpine
    restart: always
