FROM stono/hawkeye:0.12.8

# Install hawkeye
RUN mkdir -p /app
WORKDIR /app
ENTRYPOINT ["node", "oneshot.js"]

COPY package.json /app

RUN cd /app && \
    npm install --quiet --production

COPY ./ /app
