version: '2'

services:
  hawkeye:
    image: stono/hawkeye.ninja
    build: .
    environment:
      - GITHUB_SECRET
      - GITHUB_CLIENTID
      - GITHUB_CALLBACK_URL
    ports:
      - 5000
    volumes:
      - ./lib:/app/lib
