ARG HE_VERSION=
FROM stono/hawkeye:$HE_VERSION

# Install hawkeye
RUN mkdir -p /app
WORKDIR /app
ENTRYPOINT ["node", "oneshot.js"]

COPY package.json /app

RUN cd /app && \
    npm install --quiet --production

COPY ./ /app
